# Yarn configuration to suppress known warnings
# These warnings are expected for VS Code/Cursor extensions and don't affect functionality

logFilters:
  - code: "YN0071"  # Suppress "No license field" warning
  - code: "YN0072"  # Suppress "Invalid engine" warning
